services:
  postgres:
    container_name: complaint-management-db
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: complaint_management
    ports:
      - "5432:5432"
    volumes:
      - complaint_management_pgdata:/var/lib/postgresql/data

volumes:
  complaint_management_pgdata:
